pipeline{
    environment{

    }
    stages{
        stage('Login'){
            steps{
                // sh 'source .env'
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
                }
        }
        stage('Pull image'){
            steps{
                sh 'docker pull borisvikvik/penguins-data-science:latest'
            }
        }
        stage('Run container'){
            steps{
                sh 'docker run --name penguins-data-science -p 8080:5556'
            }
        }
    }
    post{
        always{
            sh 'docker stop penguins-data-science '
        }
    }
}
