pipeline {
    agent any
    stages {
        stage('Clone github repository') {
            steps {
                // cleanWs()
                sh 'git clone -b main https://github.com/BorisVIkVik/Pinguins_Data_Science'
				}
			}

        stage('Checkout repo dir') {
            steps {
                sh 'cd Pinguins_Data_Science && ls'
				}
			}
    }

}
